services:
  argo:
    image: xarkai/argo:main
    container_name: argo
    volumes:
      - argo:/root/.argo
    ports:
      - 38888:8080
    environment:
      - 'OLLAMA_BASE_URL=http://localhost:11434'
      - 'USE_HF_MIRROR=false'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always

volumes:
  argo: {}