services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  argo:
    image: xark/argo:main
    container_name: argo
    volumes:
      - argo:/root/.argo
    depends_on:
      - ollama
    ports:
      - 38888:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'USE_ARGO_OLLAMA=true'
      - 'USE_HF_MIRROR=true'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  argo: {}