"""empty message

Revision ID: 067bf581f236
Revises: c2dfc34fa5bb
Create Date: 2024-12-17 21:32:34.788787

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "067bf581f236"
down_revision: Union[str, None] = "c2dfc34fa5bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge", sa.Column("folder", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge", "folder")
    # ### end Alembic commands ###
