"""empty message

Revision ID: 142e1feb0db3
Revises: fb7d836b0e3e
Create Date: 2024-09-20 11:02:11.864167

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "142e1feb0db3"
down_revision: Union[str, None] = "fb7d836b0e3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("download_info", sa.JSON(), nullable=True))
    op.add_column("users", sa.Column("credentials", sa.JSON(), nullable=True))
    op.add_column("users", sa.Column("credentials_reachable", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "credentials_reachable")
    op.drop_column("users", "credentials")
    op.drop_column("models", "download_info")
    # ### end Alembic commands ###
