"""empty message

Revision ID: 2fc6bddd43cb
Revises: 54a577bfb146
Create Date: 2025-06-30 14:32:00.605886

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fc6bddd43cb"
down_revision: Union[str, None] = "54a577bfb146"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("agent_mode", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "agent_mode")
    # ### end Alembic commands ###
