"""empty message

Revision ID: 37628c2fd6e4
Revises: f64687ebdd30
Create Date: 2024-12-04 17:51:06.046882

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37628c2fd6e4"
down_revision: Union[str, None] = "f64687ebdd30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge", sa.Column("provider", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge", "provider")
    # ### end Alembic commands ###
