"""empty message

Revision ID: 45c5272d5b0f
Revises: 8d83e6960d6a
Create Date: 2025-01-14 20:21:59.324749

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45c5272d5b0f"
down_revision: Union[str, None] = "8d83e6960d6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_model_configs", sa.Column("silly_character", sa.JSON(), nullable=True))
    op.add_column("bots", sa.Column("background_img", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bots", "background_img")
    op.drop_column("bot_model_configs", "silly_character")
    # ### end Alembic commands ###
