"""empty message

Revision ID: 50b096bf85bb
Revises: c4e0e700a977
Create Date: 2025-05-12 14:54:18.889718

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50b096bf85bb"
down_revision: Union[str, None] = "c4e0e700a977"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("file_size", sa.BIGINT(), nullable=True))
    op.add_column("file", sa.Column("file_size", sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "file_size")
    op.drop_column("document", "file_size")
    # ### end Alembic commands ###
