"""empty message

Revision ID: 72a031253ae3
Revises: 8df4cc122a16
Create Date: 2025-04-15 19:12:28.163963

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72a031253ae3"
down_revision: Union[str, None] = "8df4cc122a16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mcp_server_config", sa.Column("headers", sa.JSON(), nullable=True))
    op.add_column("mcp_server_config", sa.Column("tools", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mcp_server_config", "tools")
    op.drop_column("mcp_server_config", "headers")
    # ### end Alembic commands ###
