"""empty message

Revision ID: 73d3fb2f927f
Revises: 48c867081066
Create Date: 2024-09-26 15:15:50.375068

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73d3fb2f927f"
down_revision: Union[str, None] = "48c867081066"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "credentials_reachable")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("credentials_reachable", sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
