"""empty message

Revision ID: 777554c73cd5
Revises: c0d0a2918105
Create Date: 2025-04-11 10:26:13.776172

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

import models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "777554c73cd5"
down_revision: Union[str, None] = "c0d0a2918105"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_server_config",
        sa.Column("id", models.sqlalchemy_types.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("description_en", sa.String(), nullable=True),
        sa.Column("command_type", sa.String(), nullable=True),
        sa.Column("command", sa.String(), nullable=True),
        sa.Column("env", sa.JSON(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("enable", sa.Boolean(), nullable=True),
        sa.Column("preset", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="mcp_server_pkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mcp_server_config")
    # ### end Alembic commands ###
