"""empty message

Revision ID: 87213f2ccd3b
Revises: d4a81702a06c
Create Date: 2024-12-04 11:34:05.416222

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87213f2ccd3b"
down_revision: Union[str, None] = "d4a81702a06c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge", sa.Column("top_k", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge", "top_k")
    # ### end Alembic commands ###
