"""empty message

Revision ID: 8d3e45886dbf
Revises: e7be07786c08
Create Date: 2024-10-10 14:18:39.274340

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d3e45886dbf"
down_revision: Union[str, None] = "e7be07786c08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_model_configs", sa.Column("user_input_form", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_model_configs", "user_input_form")
    # ### end Alembic commands ###
