"""empty message

Revision ID: 9334b7aa230c
Revises: bcda8d1d5990
Create Date: 2025-01-20 10:50:37.603870

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9334b7aa230c"
down_revision: Union[str, None] = "bcda8d1d5990"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("chat_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "chat_metadata")
    # ### end Alembic commands ###
