"""empty message

Revision ID: 93f9fea6d9f0
Revises: e6b3574deaa5
Create Date: 2024-10-17 19:50:32.681431

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93f9fea6d9f0"
down_revision: Union[str, None] = "e6b3574deaa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("auto_modelfile", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "auto_modelfile")
    # ### end Alembic commands ###
