"""empty message

Revision ID: 9644b43640d2
Revises: 927a88f19f6f
Create Date: 2025-07-23 10:39:47.982851

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

import models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9644b43640d2"
down_revision: Union[str, None] = "927a88f19f6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guest_users", sa.Column("bot_id", models.sqlalchemy_types.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guest_users", "bot_id")
    # ### end Alembic commands ###
