"""empty message

Revision ID: a7b79196fc23
Revises: 72a031253ae3
Create Date: 2025-04-16 20:06:28.339784

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7b79196fc23"
down_revision: Union[str, None] = "72a031253ae3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mcp_server_config", sa.Column("install_status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mcp_server_config", "install_status")
    # ### end Alembic commands ###
