"""empty message

Revision ID: aa94ccbf920b
Revises: 777554c73cd5
Create Date: 2025-04-14 17:46:53.914742

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa94ccbf920b"
down_revision: Union[str, None] = "777554c73cd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("tools", sa.JSON(), nullable=True))
    op.add_column("message_agent_thoughts", sa.Column("tool_type", sa.String(), nullable=True))
    op.add_column("message_agent_thoughts", sa.Column("tool_meta", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message_agent_thoughts", "tool_meta")
    op.drop_column("message_agent_thoughts", "tool_type")
    op.drop_column("conversations", "tools")
    # ### end Alembic commands ###
