"""empty message

Revision ID: bcda8d1d5990
Revises: 45c5272d5b0f
Create Date: 2025-01-17 14:12:03.812485

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcda8d1d5990"
down_revision: Union[str, None] = "45c5272d5b0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_model_configs", sa.Column("plugin_config", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_model_configs", "plugin_config")
    # ### end Alembic commands ###
