"""empty message

Revision ID: c0d0a2918105
Revises: c1beb909e1e2
Create Date: 2025-03-20 16:19:38.931486

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0d0a2918105"
down_revision: Union[str, None] = "c1beb909e1e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("is_stopped", sa.Boolean(), nullable=True))
    op.add_column("messages", sa.Column("query_deleted", sa.Boolean(), nullable=True))
    op.add_column("messages", sa.Column("answer_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "answer_deleted")
    op.drop_column("messages", "query_deleted")
    op.drop_column("messages", "is_stopped")
    # ### end Alembic commands ###
