"""empty message

Revision ID: c22785dbe150
Revises: 2fc6bddd43cb
Create Date: 2025-08-21 14:38:30.317756

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa


import models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c22785dbe150'
down_revision: Union[str, None] = '2fc6bddd43cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_users',
    sa.Column('id', models.sqlalchemy_types.GUID(), nullable=False),
    sa.Column('bot_id', models.sqlalchemy_types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='guest_user_pkey')
    )
    op.create_table('sites',
    sa.Column('id', models.sqlalchemy_types.GUID(), nullable=False),
    sa.Column('bot_id', models.sqlalchemy_types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='site_pkey')
    )
    op.create_index('site_bot_id_idx', 'sites', ['bot_id'], unique=False)
    op.create_index('site_code_idx', 'sites', ['code', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('site_code_idx', table_name='sites')
    op.drop_index('site_bot_id_idx', table_name='sites')
    op.drop_table('sites')
    op.drop_table('guest_users')
    # ### end Alembic commands ###
