"""empty message

Revision ID: c2dfc34fa5bb
Revises: 77068a445cf5
Create Date: 2024-12-16 11:23:34.752080

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2dfc34fa5bb"
down_revision: Union[str, None] = "77068a445cf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("provider", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "provider")
    # ### end Alembic commands ###
