"""empty message

Revision ID: c4e0e700a977
Revises: a7b79196fc23
Create Date: 2025-04-25 11:16:49.170067

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4e0e700a977"
down_revision: Union[str, None] = "a7b79196fc23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("ollama_template", sa.Text(), nullable=True))
    op.add_column("models", sa.Column("ollama_architecture", sa.String(), nullable=True))
    op.add_column("models", sa.Column("ollama_parameters", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "ollama_parameters")
    op.drop_column("models", "ollama_architecture")
    op.drop_column("models", "ollama_template")
    # ### end Alembic commands ###
