"""empty message

Revision ID: d4a81702a06c
Revises: f64687ebdd30
Create Date: 2024-11-25 19:10:49.862564

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4a81702a06c"
down_revision: Union[str, None] = "f64687ebdd30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledge", sa.Column("chunk_size", sa.BIGINT(), nullable=True))
    op.add_column("knowledge", sa.Column("chunk_overlap", sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledge", "chunk_overlap")
    op.drop_column("knowledge", "chunk_size")
    # ### end Alembic commands ###
