"""empty message

Revision ID: d998735c8b09
Revises: 9334b7aa230c
Create Date: 2025-02-24 11:00:20.436504

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d998735c8b09"
down_revision: Union[str, None] = "9334b7aa230c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bots", sa.Column("locked", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bots", "locked")
    # ### end Alembic commands ###
