"""empty message

Revision ID: e6b3574deaa5
Revises: 8d3e45886dbf
Create Date: 2024-10-15 15:17:10.728738

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6b3574deaa5"
down_revision: Union[str, None] = "8d3e45886dbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_model_configs", sa.Column("tool_config", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_model_configs", "tool_config")
    # ### end Alembic commands ###
