"""empty message

Revision ID: e7be07786c08
Revises: 73d3fb2f927f
Create Date: 2024-10-09 16:30:39.710437

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7be07786c08"
down_revision: Union[str, None] = "73d3fb2f927f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_model_configs", sa.Column("advanced_prompt", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_model_configs", "advanced_prompt")
    # ### end Alembic commands ###
