"""empty message

Revision ID: f64687ebdd30
Revises: 027b52c97f1d
Create Date: 2024-11-04 17:56:39.428121

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f64687ebdd30"
down_revision: Union[str, None] = "027b52c97f1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bot_model_configs", sa.Column("prologue", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bot_model_configs", "prologue")
    # ### end Alembic commands ###
