"""empty message

Revision ID: fb7d836b0e3e
Revises: b93cf3c1dcdf
Create Date: 2024-09-05 14:41:33.568192

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb7d836b0e3e"
down_revision: Union[str, None] = "b93cf3c1dcdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models", sa.Column("download_speed", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models", "download_speed")
    # ### end Alembic commands ###
